
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

redcarpet:
  extensions: ["with_toc_data"]

# Permalinks
#permalink:           /:title.html
#relative_permalinks: true

# Setup
timezone:            US/Eastern
locale:              en_us
name:				         Reality Media
title:               Reality Media
tagline:             'Augmented and Virtual Reality'
description:         'How augmented reality and virtual reality are taking their places in contemporary media culture alongside film and television'
url:                 https://realitymedia.digital
#rss:                 rss feed url
baseurl:             ''
baseurl_img:         '/assets/images'
baseurl_posts_img:   '/assets/images/posts'
baseurl_book_img:   '/assets/images/book'
baseurl_featured_img: '/assets/images/hero'
baseurl_featured_thumbnail: '/assets/images/thumbnail'
baseurl_javascripts: '/assets/javascripts'
#icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
#disqus:              disqus_shortname # get it on https://disqus.com/admin/

repository: realitymediabook/realitymediabook.github.io
utterances:
  theme: "boxy-light"
  issue_term: "realitymediabook/realitymediabook.github.io"

author:
  name:           	 Jay Bolter, Maria Engberg and Blair MacIntyre
  url:            	 https://mitpress.mit.edu/books/reality-media
  # facebook:          username
  twitter:           blairmacintyre
  # linkedin:          username

# Server
destination:      	 ./docs
exclude:          	 [vendor, ".gitignore", "CONTRIBUTING.md", "CNAME", "LICENSE", "gulpfile.js", "package.json", "package-lock.json", "node_modules", "README.md", "sass", "docs", "old", "Gemfile", "Gemfile.lock"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

collections:
  chapters:
    output: true
  appendices:
    output: true
  pages:
    output: true